{% set name = "memprof" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a8376ce476bf82a5eb465d1a30b8ffc86cc55b0b6de7aa4cdeccb4c99586d967

build:
  number: 7
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python
    - matplotlib-base
    - setuptools

test:
  imports:
    - memprof
  commands:
    - python -m memprof --help
    - mp_plot --help

about:
  home: https://jmdana.github.io/memprof/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: 'A memory profiler for Python. As easy as adding a decorator.'
  dev_url: https://github.com/jmdana/memprof

extra:
  recipe-maintainers:
    - kynan
