{% set name = "memprof" %}
{% set version = "0.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ec5e39eae7ad8c126ee179e6e50f06755503ce10f79dee320fea44034507834

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - cython
  run:
    - python
    - matplotlib

test:
  imports:
    - memprof
  commands:
    - python -m memprof --help
    - mp_plot --help

about:
  home: https://jmdana.github.io/memprof/
  license: GPL 3
  license_family: GPL3
  license_file: LICENSE
  summary: 'A memory profiler for Python. As easy as adding a decorator.'
  dev_url: https://github.com/jmdana/memprof

extra:
  recipe-maintainers:
    - kynan
