travis:
  secure:
    BINSTAR_TOKEN: P6aC79xcBK/BJ6iFB8YNqE/3X+Lsen9KFQoM4KaP+luy3RgfO3NUjHsa7L50znV/PWrbj4pDoqDDWDqxN+IP9Ud4vmGI89AZcBDBmSwlH8EvivfaCzRE+Nfn9gfxRgW0hIJxk7oYLqRFlJuQLHL8dlGBX7zsGYfq/NK1NJvfCZ9IGVPcrSejq7z6Sb3pFP39EDEhfUTOhopfcPH67Zrp1NnuAU1QsO7fDZaRB/J7KmTgx9CvhriH3BDsRU4nam4S7Zu6BwcuMZDnmHU5Su94cCZI+J8NsAUivthLhjrzd04qRe7HG4zL606URjoYIYPQuMbXgp+mD0erFHetzmzUM2nagrqL43w5pdb0frwrKEtnBOxs6O/NRY/0dTFQYtFgE1wCjLvqoph4neh3cxD/F6Bn71tcKqgOKEanZO8+QQcfEpzmWyHhk4/ZjLOZyztwbt8O59IpcY/hSVsOHNw240Q/3Ia/gejuJA0YUgX8sZDpfZiWqvMe9s6pbhxXU9reRjaRTnWyIkk/rhFwTA08wTaMoDcy6YSZ6K02XnY+vr6Rs8c5GVXRoVkkFFK3QCdwcEk6aujwYweq7p/ZF+hEUDmfDI9sVV7BRTMmsmuex/OBW6WqIeFSmAof3uuu6jKHpaFexkFQFsTjvM6OkAe+H4RosFZ1L7+LzGhgRbigzME=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
