travis:
  secure:
    BINSTAR_TOKEN: nXz2eesyjWOgXmqdXsb1SsTHlIf4aMG/O7z69n8P6hE+sEn/hzIQP1QA0A1Hj7GjbRyPHV4prsJfLg/4SYZjfCfzZq87vy2kUwYaEyCh4gv7hTF7d3H8ZL77Ika20Fbo7DM5ehZCTARxUx9ef2tBgcYNZwfpLqRKCBcBXt0iVZeypa1Xac34bigmozfsFENprZzdzbFb9iKIc+A0mXIiI8lSo6ZNMwHibr4fA4r7+Qn8RYL9/rbrNdxBKZ7onNj0uOGr+Jf5y4BubaZGf2OsRBIpOWwPYbqDC/8DLFEKmJD+zySp0zlqdDTjjv0fp2SjLTBX3QMAKQpjflTUCxmdZHDG2nHmERXCyrIjjMqNfKd/81bJCyVkDUEV2s0H/CjNs6ksqYBI+LvUoOe7PJ5LlM6+WYd+7yF2NPXccGvdNS79LnxyexAmGijRQTyH7Q2mSnYf5MMv3tGpTLIri34yTG8VUAFZ1IldoSJiusOsYE83xJMYvBzTqzShwTObLPzWqQ+zt0EKV8GWcHLMU8VpxSIAe6f7jvm+jOdMqt+vnRNJ2pw5ns8xv4Ka6CK3O69kt8S1iX61ZTYc8h18dlb8lGKNyjX46RiYjm1bXQZ6CI8sypHVXFBL5XcF2WsKsCojDtgrL3zeXIpYSSBgbVSMBE3d5IryQQ/xqfO6dyHDl3k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
